//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets.RTSCore.Misc
{
	public enum HUDRegions {GameArea, OrdersBar, MiniMap, ResourceBar, InventoryManager, ProductionManager, GalacticMarketBoard, Invalid}
	public enum UnitState { Finished, Stopped, Walking, ProvidingService }
	public enum BuildingState {Working, NotWorking}
	public enum ProductionState {Started, Paused, NotStarted}
	public enum NotFunctioningReason {NeedMaterials, NeedLabor}
	public enum PriorityLevel {None, Low, Medium, High}
	public enum RequestState {Posted, Accepted, InProcess, Filled, Complete, OnHold}
}

